services:
#    badge.example:
#        class: Rem\BadgeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    badge.manager:
        class: Rem\BadgeBundle\Manager\BadgeManager
        arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher']